### ISSUE TITLE
Unique friendly name for aligenie

### ISSUE THREAD

**Issue by mcdull** [feversky/aligenie#1]
Is it possible to retain "English" friendly name so that the device could be used by Google Assistant or Amazon Echo?  Is it possible to define aligenie_friendlyname to specify name required by aligenie?  Thank you.

**Comment by feversky** [comment]
you can use following keywords to explicitly define behaviors or returns of the plugin:
hagenie_hidden
hagenie_zone
hagenie_deviceType
hagenie_deviceName
hagenie_propertyName

in your case, hagenie_deviceName is the right one.

**Comment by feversky** [comment]
> Is it possible to retain "English" friendly name so that the device could be used by Google Assistant or Amazon Echo? Is it possible to define aligenie_friendlyname to specify name required by aligenie? Thank you.

you can use following keywords to explicitly define behaviors or returns of the plugin:
hagenie_hidden
hagenie_zone
hagenie_deviceType
hagenie_deviceName
hagenie_propertyName

in your case, hagenie_deviceName is the right one.

**Comment by feversky** [comment]
closed
