### ISSUE TITLE
天猫精灵获取不到设备

### ISSUE THREAD

**Issue by kylinfedora** [feversky/aligenie#2]
你好！我在论坛提问了，目前我的天猫精灵获取不到设备
https://bbs.hassbian.com/forum.php?mod=viewthread&tid=4758&extra=&highlight=%E5%A4%A9%E7%8C%AB%E7%B2%BE%E7%81%B5&page=22

**Comment by feversky** [comment]
开发者网关地址错误

**Comment by kylinfedora** [comment]
> 开发者网关地址错误
配置如下：
![image](https://user-images.githubusercontent.com/2525979/56470655-60d77a00-647b-11e9-86eb-852d3c24b881.png)
还是看不到设备：
![image](https://user-images.githubusercontent.com/2525979/56470668-895f7400-647b-11e9-8135-71250e469f73.png)
HA上的设备：
![image](https://user-images.githubusercontent.com/2525979/56470693-bdd33000-647b-11e9-9547-02bb3a7b90c8.png)

**Comment by feversky** [comment]
请仔细阅读帖子，并提供日志

**Comment by kylinfedora** [comment]
麻烦看下，您的帖子我也仔细研读过，但是目前还是和上面一样看不到设备
HA的版本信息：
![image](https://user-images.githubusercontent.com/2525979/56548005-81a1eb80-65b1-11e9-917b-f849fc333e75.png)

configuration.yaml配置：
![image](https://user-images.githubusercontent.com/2525979/56547923-53bca700-65b1-11e9-999c-eb20b9592a1e.png)

customize.yaml配置：
![image](https://user-images.githubusercontent.com/2525979/56548130-d7769380-65b1-11e9-8771-9b4b79315063.png)


天猫精灵真机测试连接后的日志：
![image](https://user-images.githubusercontent.com/2525979/56547812-0dffde80-65b1-11e9-90b3-70bc47aa7e8a.png)

**Comment by kylinfedora** [comment]
问题解决了
1.更新了您的脚本
2.删除了__pycache__文件夹
