### ISSUE TITLE
成功在天猫精灵里面添加了一个light的设备，但是无法用天猫精灵控制

### ISSUE THREAD

**Issue by hsxsix** [feversky/aligenie#4]
使用的mqtt方式添加的一个ESP8266做的彩灯，在home assistant能够正常控制、调颜色亮度，天猫精灵app里也找到了这个设备，但是无法控制
![Screenshot_2019-05-09-10-03-00-1464603320](https://user-images.githubusercontent.com/18223109/57422299-19eed000-7242-11e9-867c-9003d5ecca63.png)
![Screenshot_2019-05-09-10-02-55-0001639710](https://user-images.githubusercontent.com/18223109/57422306-2115de00-7242-11e9-9749-3aa430e8670c.png)

**Comment by feversky** [comment]
hi, 请给出log日志，这样方便分析。

**Comment by hsxsix** [comment]
sorry，是无法在天猫精灵的app里控制，天猫精灵音箱可以语音控制了，谢谢大大的代码

**Comment by feversky** [comment]
天猫精灵app好像不能直接控制吧。可以使用Chrome访问网页，或者在Google play里面找home assistant的客户端。

**Comment by hsxsix** [comment]
是的，感谢你的答复
