### ISSUE TITLE
How to register a AliGenie Voice Developer account in https://open.aligenie.com/?

### ISSUE THREAD

**Issue by jerrychong25** [feversky/aligenie#6]
Hi,

Do you mind to share how a foreigner can register a AliGenie Voice Developer account in https://open.aligenie.com/?

In the registration page, the verification documents only opens to China, Hong Kong, Macau & Hong Kong, as per screenshot below:
![AliGenie Registration Page](https://user-images.githubusercontent.com/15714095/58769891-eb180f80-85dd-11e9-97e9-3849651e7889.png)

As a foreigner, I can’t register an account as I don’t own a China identification document for verification purpose.

Thanks.

**Comment by feversky** [comment]
Hi,

I'm not the member of the company.
I guess you can try to send email to aligenie@list.alibaba-inc.com to apply for a new account.

**Comment by jerrychong25** [comment]
Hi,

Noted and thanks.

**Comment by shingz96** [comment]
> Hi,
> 
> Noted and thanks.

hi @jerrychong25 , could u able to register account by sending email to aligenie@list.alibaba-inc.com?

**Comment by jerrychong25** [comment]
> > Hi,
> > Noted and thanks.
> 
> hi @jerrychong25 , could u able to register account by sending email to [aligenie@list.alibaba-inc.com](mailto:aligenie@list.alibaba-inc.com)?

Hi @shingz96,

Unfortunately, nope.
